version: '3.7'
services:
  backend:
    container_name: backend
    build:
      context: .
    command: yarn start:dev
    volumes:
      - .:/usr/src/app
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    restart: unless-stopped
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_DB=${POSTGRES_DB}'
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres:/data/postgres
volumes:
  postgres:
